---
title: "Revolution cause determination"
author: "Sam McKay"
date: "22/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
rm(list=ls())
library(ggplot2)
library(plyr)
library(scales)
library(sads)
library(reshape2)
library(tidyr)
library(broom)
library(dplyr)
library(flexmix)
library(data.table)
library(naniar)
```
options(mc.cores=parallel::detectCores())

Load Data (Produced using "Revolutions variable importance estimator.R")
```{r}
data<-fread("ecology_revolution_dropout.csv", header=TRUE) #data was subset to evolution papers in importance estimator
data<-arrange(data, excl_var, year)
```
Replace excluding topic names with numbers to 
```{r}
excluded_topic<-data$excl_var
excluded_topic <- as.numeric(substring(excluded_topic, 6))
excluded_topic<-as.data.frame(excluded_topic)
excluded_topic[is.na(excluded_topic)]=0
```
Add temp as column
```{r}
d<-cbind(data,excluded_topic)
d<-d%>% arrange(excluded_topic)
d <-d%>% replace_with_na(replace = list(revcons = c("NA")))
d$revcons<- factor(d$revcons, levels = c("rev", "cons"))
```

```{r}
sig<-subset(d[c(10,11)])
sig<-as.data.frame(sig)
sig<-subset(sig, revcons=="rev")
FNcount<-table(sig)
FNcount<-as.data.frame(FNcount)
FNcount<-FNcount%>%
  arrange(Freq)
```
Make palettes
````{r}
greys<-floor(seq(from=90, to=1, length.out=30))
greys<-paste("grey", greys, sep="")
pal1<-c(greys)
pal2<-c("indianred3", "steelblue3")
```
```{r}
 Revolution.plots<-function(d,save.directory = 'Ecology fnplots.pdf'){
   pdf(save.directory)
  for (i in c(0,levels(as.factor(d$excluded_topic)))){
  if(i ==0){
    title<-(paste("FNplot of all ecology papers"))
  }
  else{
    title<-(paste("FNplot of ecolog papers excl. topic", i ))
  }
   res_full<-subset(d, excluded_topic==i)
    fnplot2<-ggplot()+
    geom_tile(data=res_full, aes(x=year,y=hw,fill=as.factor(bin)))+
    scale_fill_manual(values=c(pal1), na.value=NA)+
    geom_point(data=res_full, aes(x=year,y=hw, colour=as.factor(revcons)), size=2, alpha=1)+
    scale_colour_manual(values=c(pal2))+
    ylab("k")+
    xlab("year")+
    ggtitle(title)+
    guides(colour=FALSE, fill=FALSE)+
    #geom_rect(aes(xmin=1895, xmax=1905, ymin=0, ymax=20), fill="red", alpha=0.2)+ #revolution 1
    #geom_rect(aes(xmin=1950, xmax=1994, ymin=0, ymax=59), fill="red", alpha=0.2)+ #revolution 1
    scale_x_continuous(breaks=pretty_breaks(n=5), limits=c(min(res_full$year), max(res_full$year)))+#
    scale_y_continuous(breaks=pretty_breaks(n=10), limits=c(0, max_k))+
    theme_classic(base_size = 12, base_family = "sans")+
    theme(axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'), legend.position="bottom", text=element_text(size=10,  family="sans", colour = 'black'))
    print(fnplot2)
  }
   dev.off()
 }
```
```{r}
Revolution.plots(d)
```
